###
GET http://localhost:3000/conta/listar/


###
GET http://localhost:3000/conta/buscar/333333

###
POST http://localhost:3000/conta/cadastrar
Content-Type: application/json

{
    "primeiroNome" : "Liandra",
    "sobrenome" : "abc",
    "CPF" : "333333",
    "telefone" : "9999999",
    "chave": [
        "AAAAAAA", "hggh"
    ] 
    
}

###
PUT http://localhost:3000/conta/atualizar/333333
Content-Type: application/json

{
    "primeiroNome" : "Gold Roger",
    "sobrenome" : "abc",
    "CPF" : "123123",
    "telefone" : "9999999",
    "chavepix" : "segundachave"
}

###
DELETE http://localhost:3000/conta/deletar/123123
