###
GET http://localhost:3000/conta/listar/


###
GET http://localhost:3000/conta/buscar/1234

###
POST http://localhost:3000/conta/cadastrar
Content-Type: application/json

{
    "primeiroNome" : "Alex",
    "sobrenome" : "aaa",
    "CPF" : "02",
    "telefone" : "9999999",
    "PIX": "pixpixp"
}

###
PUT http://localhost:3000/conta/atualizar/333333
Content-Type: application/json

{
    "primeiroNome" : "Gold Roger",
    "sobrenome" : "abc",
    "CPF" : "123123",
    "telefone" : "9999999",
    "chavepix" : "segundachave"
}


###
DELETE http://localhost:3000/conta/deletar/123123
