###
GET http://localhost:3000/conta/listar/


###
GET http://localhost:3000/conta/buscar/123123

###
POST http://localhost:3000/conta/cadastrar
Content-Type: application/json

{
    "primeiroNome" : "Franciele",
    "sobrenome" : "Silveira",
    "CPF" : "123123",
    "telefone" : "9999999",
    "chavepix" : [
        {
            "tipoChave" : "CPF",
            "chave" : "123"
        }
    ] 
}